[project]
name = "pac-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8>=7.3.0",
    "mypy>=1.20.2",
    "ursina>=8.3.0",
]

[[tool.mypy.overrides]]
module = "ursina.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "src.visualization"
disallow_subclassing_any = false
